version: '3'

services:
  mongodb:
    image: mongo:7.0.3
    container_name: dimatica-mongodb-code-challenge
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: mongodb_data
